# Generated by Django 5.0.3 on 2024-04-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_valk_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='valk',
            name='color_hex',
            field=models.IntegerField(default=15418783, max_length=8),
        ),
    ]
